### ISSUE TITLE
Got Use of undefined constant MB

### ISSUE THREAD

**Issue by sudipta26889** [getkirby/toolkit#103]
ErrorException in str.php line 391:
Use of undefined constant MB - assumed 'MB'

**Comment by bastianallgeier** [comment]
Which branch do you use?

**Comment by sudipta26889** [comment]
master

**Comment by bastianallgeier** [comment]
do you include the boostrap.php or just the str class?

**Comment by sudipta26889** [comment]
i want to use str class only

**Comment by lukasbestle** [comment]
Please use `bootstrap.php`. If you only use `Str`, then only this class is auto-loaded.
