### ISSUE TITLE
Creating subpage with fixed template gives error but succeeds

### ISSUE THREAD

**Issue by MrApe** [getkirby/toolkit#104]
I'm trying to create a sub-page with a fixed template (defined in blueprint) and the frontend reports an `unexpected error`:
![issue](https://cloud.githubusercontent.com/assets/98466/10310497/7ef2326c-6c42-11e5-99da-2863f007e60d.png)

However, the site is created and shows up upon page reload.

The apache error log says:

`[Tue Oct 06 15:52:45.874366 2015] [:error] [pid 2766] [client ...] PHP Warning:  preg_match() expects parameter 2 to be string, array given in /var/www/html/kirby/toolkit/lib/data.php on line 102, referer: https://[...]/panel/
[Tue Oct 06 15:52:45.874578 2015] [:error] [pid 2766] [client ...] PHP Warning:  trim() expects parameter 1 to be string, array given in /var/www/html/kirby/toolkit/lib/data.php on line 106, referer: https://[...]/panel/`

How do I get rid of this error message, since anythings seems to be fine. By the way: page creation in any other page or subpage works fine.

**Comment by bastianallgeier** [comment]
Could you send me an email: bastian@getkirby.com I need to look deeper into this.
