### ISSUE TITLE
ImageMagick driver without `exec()`

### ISSUE THREAD

**Issue by iksi** [getkirby/toolkit#106]
Wondering if it is planned to change the ImageMagick thumb driver to use the PHP-extension Imagick instead of a shell command through `exec()`. A lot of servers disable `exec()` as a part of their security measures. If it is not planned/being worked on I’ll build that thumb driver myself.

**Comment by bastianallgeier** [comment]
I think it would be best to have a separate driver for that. My experience at least with most German and a lot of US shared hosting providers is that they don't have the Imagick extension installed for PHP, which sucks big time.

**Comment by iksi** [comment]
Thanks for the speedy reply. I’ll build one as a plugin then!

**Comment by bastianallgeier** [comment]
:+1:
