### ISSUE TITLE
Allow for multilingual niceSize()

### ISSUE THREAD

**Issue by PaulMorel** [getkirby/toolkit#113]
I'm currently building a bilingual website that has to adhere to government accessibility and language standards, which means **everything** has to be both in English and French, including file sizes.

For the moment I've hacked together my own `niceSize()` function that checks which language is being used at the moment, however I think it could be a worthwhile addition to the toolkit in the future.

Here are the units for French. The lowercase `k` for `ko` is intentional.

` $unit = array('o', 'ko', 'Mo', 'Go', 'To', 'Po', 'Eo', 'Zo', 'Yo');`

**Comment by lukasbestle** [comment]
Oh yes, the French octet. :D

I think this should be implemented with an optional config option (like `c::set('filesize.units', array(...))`). You would be able to set this option in your language file to override the built-in value array.

**Comment by bastianallgeier** [comment]
I've just added a fix for this to the develop branch. 

You can now change the units yourself in your language file for example, by doing this: 

```php
f::$units = array('o', 'ko', 'Mo', 'Go', 'To', 'Po', 'Eo', 'Zo', 'Yo');
```
