### ISSUE TITLE
Get width, height and ratio from SVG images

### ISSUE THREAD

**Issue by JimmyRittenborg** [getkirby/toolkit#115]
I think it would be really neat if we could get the width and height from SVG images from either its width and height or viewbox attributes.

Im using this for example with header logos, to get its ratio to make it responsive in a non painting manor - browser paints are expensive on mobil, especially in the header (critical path) where they're visually present.

```php
$site->image('site-logo.svg')->width();
$site->image('site-logo.svg')->height();
$site->image('site-logo.svg')->ratio();
...
```

**Comment by bastianallgeier** [comment]
Oh, I never thought about actually parsing the SVG code in order to get the width and height. That's a great idea!!

**Comment by bastianallgeier** [comment]
I just added width and height detection for SVGs to the develop branch :)

**Comment by JimmyRittenborg** [comment]
That is so cool! I'm excited for this. Thanks :+1:

**Comment by JimmyRittenborg** [comment]
This could maybe be extended a bit further actually.
```php
$site->image('icons.svg#map-marker')->width();
..
```
Could do the same but for an element within the `<svg>` with an id of `map-marker` :tada:

**Comment by JimmyRittenborg** [comment]
It would also be pretty neat if parts or the entire `viewBox="x y width height"` could be grabbed, this is not only scoped at `<svg>` elements but also multiple `<symbol>` within it though.
