### ISSUE TITLE
Move new thumb generation methods to `Media` class

### ISSUE THREAD

**Issue by lukasbestle** [getkirby/toolkit#125]
See [this topic in the forum](https://forum.getkirby.com/t/user-avatar-resizing/2767?u=lukasbestle).

The methods are currently defined in the `File` class, which inherits from `Media`. To make the avatars work (and also because it simply makes sense), I think we could move the methods `resize` and `crop` to `Media`.

**Comment by bastianallgeier** [comment]
This is so much better. Just added it to the develop branch.
