### ISSUE TITLE
resize() & crop() fail silently if /thumbs/ folder is missing

### ISSUE THREAD

**Issue by PaulMorel** [getkirby/toolkit#130]
As I figured out [in this topic](https://forum.getkirby.com/t/resize-or-crop-dont-seem-to-work/2818), the `resize()` and `crop()` methods on Media objects fail silently when the `/thumbs/` folder isn't present.

I'm not sure what would be best, print an error when it happens or create the missing folder.

**Comment by bastianallgeier** [comment]
The thumb class now tries to create the folder if it does not exist. I think this is the best way to make this more smooth.
