### ISSUE TITLE
Thumb::width and height methods don't use calculated values

### ISSUE THREAD

**Issue by lukasbestle** [getkirby/toolkit#136]
See [this post in the forum](https://forum.getkirby.com/t/image-embed-in-kirbytext-thumbnails-kirbytag/1574/4?u=lukasbestle).

When `crop` is not set to `true`, the Thumb class should calculate the missing value right on instantiation so that the values are correct.

**Comment by bastianallgeier** [comment]
This is solved for all Kirby resizing methods now, but returning a new image object for the thumbnail directly after creation. I plan to overhaul the thumb class as soon as possible. It's quite messy at the moment.
