### ISSUE TITLE
$page->documents()->filterBy('language', '!=', '')->toJson() calls ratio()

### ISSUE THREAD

**Issue by Pascalmh** [getkirby/toolkit#140]
This `$page->documents()->filterBy('language', '!=', '')->toJson()` seems to call the ratio() function in `kirby/toolkit/lib/dimensions.php`

```
Warning:  Division by zero in kirby/toolkit/lib/dimensions.php on line 68
```

(I am on Version 2.2.3)

**Comment by bastianallgeier** [comment]
I just fixed this on the develop branch.
