### ISSUE TITLE
Implement has() method in Collection class

### ISSUE THREAD

**Issue by texnixe** [getkirby/toolkit#142]
$pages->has() does only work in the $pages collection, not when checking in children ..., the example in the cheat sheet does not work.

**Comment by distantnative** [comment]
Would this be sufficient?
```php
  public function has($key) {
    return isset($this->data[$key]);
  }
```

And then change the implementation for pages to
```php
 public function has($page) {
    $uri = is_string($page) ? $page : $page->id();
    return parent::has($uri);
  }
```

**Comment by bastianallgeier** [comment]
I just implemented this as Nico suggested
