### ISSUE TITLE
Secure str::random

### ISSUE THREAD

**Issue by mzur** [getkirby/toolkit#153]
Maybe a more secure `str::random` function should be considered since it is used to generate the [authentication key](https://github.com/getkirby/kirby/blob/d93de5fb29b3f1dc32f941cf46b6efdc27f3ba7a/core/user.php#L145) or [CSRF tokens](https://github.com/getkirby/panel/blob/606b782e9ccd454cc732668a7f73ab19bbd98d52/app/src/panel.php#L200).

What do you think about implementing a [random](https://github.com/laravel/framework/blob/1dfb03cb4b960e1f5d4a5f7b81f39f5cb5f9e731/src/Illuminate/Support/Str.php#L223-L236) function based on [`random_bytes`](http://php.net/manual/en/function.random-bytes.php) and a [quickRandom](https://github.com/laravel/framework/blob/1dfb03cb4b960e1f5d4a5f7b81f39f5cb5f9e731/src/Illuminate/Support/Str.php#L259-L264) function for insecure stuff like Laravel does?

**Comment by bastianallgeier** [comment]
Sounds like a useful addition! I will mark this for the next release after 2.3.

**Comment by sebsel** [comment]
@lukasbestle Isn't this closed in september 2016 by https://github.com/getkirby/toolkit/pull/155?

**Comment by mzur** [comment]
It is (ref @6ac787ffbdc8cc28a62fcaccbf2d4dbbb248000c).
