### ISSUE TITLE
2.3 beta: thumb() helper returns original URL

### ISSUE THREAD

**Issue by lukasbestle** [getkirby/toolkit#159]
See [this topic](https://forum.getkirby.com/t/kirby-2-3-beta-thumbnails-of-media-objects-e-g-avatars/3885/3?u=lukasbestle).

**Comment by jbeyerstedt** [comment]
Isn’t this the same issue as getkirby/kirby#414?

**Comment by lukasbestle** [comment]
Thank you very much. It seems to be.
