### ISSUE TITLE
Replace DS by '/' on Thumb destination url

### ISSUE THREAD

**Issue by Ventricule** [getkirby/toolkit#165]
Hello,
On Windows, since 2.3.0 beta 2 the thumbs was brocken, after a look it seems to be because of a backslash in the thumb url right after '/thumbs'. 
Exemple : http://localhost/tdc/thumbs\image-800x600.jpg 

So, modified thumbs.php line 50 :
`'url'  => $self->kirby->urls()->thumbs()  . DS . $path,`
replaced by : 
`'url'  => $self->kirby->urls()->thumbs()  . '/' . $path,`
And it rock.
Its better like that, right ?

**Comment by lukasbestle** [comment]
This is a duplicate of getkirby/kirby#436. Have you tried updating to the latest version of the develop branches? Should be fixed there.

**Comment by Ventricule** [comment]
Yes that's this bug, sorry for the duplicate, thank for the fix!

**Comment by lukasbestle** [comment]
No problem, thanks for confirming.
