### ISSUE TITLE
Thumbs for files outside the content folder since 2.3.0

### ISSUE THREAD

**Issue by MathiasGmeiner** [getkirby/toolkit#166]
Before 2.3.0 it was possible to generate the thumbs as described in https://getkirby.com/docs/templates/thumbnails#thumbs-for-files-outside-the-content-folder

but after the update to 2.3.0 two things happen:
- default driver is im instead of gd (doesn't matter if gd is in the config.php)
- the root default /thumbs is not correct

This is the code I used before 2.3.0:
```
$media = new Media(
  // the absolute path for the file
  kirby()->roots()->index() .'/images/'. $image,         
  // the absolute url
  kirby()->urls()->index() .'/images/'. $image
);

$image = thumb($media, array('width' => 936, 'height' => 702, 'crop' => true, 'quality' => 40))->url();
```

and after some debugging this is the working code for 2.3.0:
```
$media = new Media(
  // the absolute path for the file
  kirby()->roots()->index() .'/images/'. $image,         
  // the absolute url
  kirby()->urls()->index() .'/images/'. $image
);

$image = thumb($media, array('width' => 936, 'height' => 702, 'crop' => true, 'quality' => 40, 'driver' => 'gd', 'root' => $_SERVER['DOCUMENT_ROOT'] .'/thumbs/'));
```

**Comment by lukasbestle** [comment]
As far as I can tell, this is the intended behavior since 2.3.0. It makes the Toolkit more independent from the CMS so that it works for users who don't also use the CMS.

Have you tried using the new `Asset` class?

```php
$asset = new Asset('images/' . $image);
$image = $asset->thumb(array('width' => 936, 'height' => 702, 'crop' => true, 'quality' => 40))->url();
```

If that works without any further changes (as it should), we will instead update the documentation.

**Comment by MathiasGmeiner** [comment]
I will try `new Asset` next week, thanks!

**Comment by MathiasGmeiner** [comment]
Works great, thanks!
