### ISSUE TITLE
Email class: CC and BCC support

### ISSUE THREAD

**Issue by lukasbestle** [getkirby/toolkit#167]
See [this post](https://forum.getkirby.com/t/php-mail-to-several-receivers/789/3?u=lukasbestle).

**Comment by CelineDesign** [comment]
+1  : a must have feature

**Comment by sebsel** [comment]
+1, needing this now :)

**Comment by bastianallgeier** [comment]
This is now implemented. Works only for one cc and one bcc address so far, but it's a first step.
