### ISSUE TITLE
Collection: chunk() method

### ISSUE THREAD

**Issue by lukasbestle** [getkirby/toolkit#175]
Inspiration from [this topic](https://forum.getkirby.com/t/array-chunk-in-foreach-dont-work/4317?u=lukasbestle).

`$collection->chunk($size)` would work like `$collection->group()`, but instead of grouping by a field it would just use `array_chunk` to make groups of `$size` items.

**Comment by fenixkim** [comment]
+1

**Comment by lukasbestle** [comment]
This will be included in Kirby 2.3.2

**Comment by jenstornell** [comment]
2.3.2 will include new features then?

**Comment by lukasbestle** [comment]
Small ones that don't modify existing code, yes.
