### ISSUE TITLE
Implement Countable Interface for Collections

### ISSUE THREAD

**Issue by tillprochaska** [getkirby/toolkit#181]
Is there a reason why the `Collection` class doesn’t implement the Countable interface? Would be great in order to improve compatibility with third-party plugins, especially as Kirby know allows you to replace its components.

**Comment by lukasbestle** [comment]
No, there is no reason. :)
It's actually a good idea and easy to do since the collection class already has a compatible `count()` method.

**Comment by lukasbestle** [comment]
This is now on the develop branch and will be included in Kirby 2.3.2.
