### ISSUE TITLE
One cannot set an attribute to 0 with html::attr

### ISSUE THREAD

**Issue by bezin** [getkirby/toolkit#192]
Hey there,

I spotted an akward issue in the html::attr method while using the [range-slider-field](https://github.com/JonasDoebertin/kirby-range-slider/). I debugged the plugin first and it is working fine ;) 

But under the hood it uses the Brick Class, where I found following issue: It is not possible to set a html attribute value to 0 even though this is valid for the min-attribute on an input range. 

~~This is due to an [empty(0) === true in html::attr](https://github.com/getkirby/toolkit/blob/master/lib/html.php#L188-L190).~~

Update: It is acutally possible to pass 0 (as Integer) to html::attr, but it is not possible to pass 0 (as float) to html:attr...

**Comment by bezin** [comment]
Ok, I did not check the plugin enough. The matter is a little bit more complicated: This issue occures due to the fact the plugin passes 0 as a float to the attribute. This way, [($value !== 0) === false](https://github.com/getkirby/toolkit/blob/master/lib/html.php#L188-L190) and hence, the attribute is not set.

**Comment by lukasbestle** [comment]
AHH, all those PHP type issues. Thanks for letting us know, we will look into this.

**Comment by lukasbestle** [comment]
This should now be fixed on the develop branch for Kirby 2.4.0.
