### ISSUE TITLE
Should toolkit provide hooks?

### ISSUE THREAD

**Issue by squiddle** [getkirby/toolkit#196]
I try to set up my kirby with content in a submodule and git-commit-and-push-content plugin.

I also added the kirby-webmentions plugin.

git-commit-and-push-content hooks into various panel hooks to decide when to commit and push changes.

kirby-webmentions uses f::write() to write its data about received webmentions.

f::write does not trigger any hooks.

The net result is inconsistency and uncommited and unpushed changes in the content submodule. Which gets problematic if i change the content submodule from the other end.

I am not sure how to go about it. If f::write would trigger some hooks, the git-commit-and-push-content plugin could just rely on those hooks as well and it would work. This seems very ad-hoc so i am not sure if the toolkit even should have hooks or not.

**Comment by bastianallgeier** [comment]
I think this should be a feature of the webmentions plugin and not of the f:: class.
