### ISSUE TITLE
PHP Error

### ISSUE THREAD

**Issue by bigflannel** [getkirby/toolkit#197]
I am trying to use invalid(). I have been working from:

https://gist.github.com/bastianallgeier/c396df7923848912393d

I have set up a contact form and it works if I don't validate the data. My data validation code is:

`$data = array (
		'name'  => get( 'name' ),
		'email' => get( 'email' ),
		'text'  => get( 'text' ),
	);
	$rules = array(
		'name'  => array( 'required ' ),
		'email' => array( 'required ', 'email' ),
		'text'  => array( 'required ' ),
	);	
	$messages = array(
		'name'  => 'Please enter your name',
		'email' => 'Please enter a valid email address',
		'text'  => 'Please enter your inquiry',
	);
	// some of the data is invalid
	if ( $invalid = invalid ( $data, $rules, $messages ) ) {	
		$alert = $invalid;	
	// the data is fine, let's send the email
	} else {
	}
}
return compact( 'alert' );`

I get the following in my logs:

mod_fcgid: stderr: PHP Fatal error: Uncaught exception 'Exception' with message 'The validator does not exist: required ' in kirby/toolkit/lib/v.php:39
mod_fcgid: stderr: Stack trace:, referer: 
mod_fcgid: stderr: #0 [internal function]: V::__callStatic('required ', Array) 
mod_fcgid: stderr: #1 [internal function]: V::required ('Mike Hartley', 'required ')
mod_fcgid: stderr: #2 kirby/toolkit/helpers.php(270): call_user_func_array(Array, Array) 
mod_fcgid: stderr: #3 kirby/toolkit/helpers.php(324): call(Array, Array)
mod_fcgid: stderr: #4 site/controllers/page.php(22): invalid(Array, Array, Array) 
mod_fcgid: stderr: #5 [internal function]: Kirby\\Registry\\Controller->{closure}(Object(Site), Object(Children), Object(Page), Array)
mod_fcgid: stderr: #6 kirby/core/page.php(1416): call_user_func_array(Object(Closure), Array)
mod_fcgid: stderr: #7 kirby/toolkit/lib/v.php on line 39

Appreciate any advice. I tried updating Toolkit etc.

Regards
Mike

**Comment by texnixe** [comment]
Try without the whitespace after `required`.

**Comment by bigflannel** [comment]
[insert ashamed face]

Thank you.

Much appreciated.

Regards
Mike
