### ISSUE TITLE
Option to prefix memcached keys

### ISSUE THREAD

**Issue by JimmyRittenborg** [getkirby/toolkit#20]
Would it make sense the to add the option to allow for prefixing memcached keys? 
I'm currently working on a Kirby multisite environment, and I can already imagine caches would collide when pages is named the same, across sites.

**Comment by bastianallgeier** [comment]
It took forever and I'm really sorry about it, but there's finally an option on the develop branch to set the memcache prefix via cache options: 

In the Kirby config you would simply do: 

```php
c::set('cache.options', array(
  'prefix' => 'mycustomprefix_'
));
```
