### ISSUE TITLE
Allow empty string as slug separator

### ISSUE THREAD

**Issue by samnabi** [getkirby/toolkit#201]
Right now, the [`str::slug()`](https://github.com/getkirby/toolkit/blob/master/lib/str.php#L508) method doesn't allow an empty string as a separator. It would be good to modify this function to differentiate between `NULL` and `''`, and allow the empty string as a separator.

Right now I'm using this function to achieve the effect: `str_replace('-', '', str::slug($string))`

**Comment by bastianallgeier** [comment]
I just implemented this on the develop branch.

**Comment by samnabi** [comment]
Thanks!
