### ISSUE TITLE
Suggestion - str::replace()

### ISSUE THREAD

**Issue by jenstornell** [getkirby/toolkit#204]
**In PHP str_replace works like this:**

```php
echo str_replace(
  array('replace_this', 'overwrite'),
  array('with_this', 'this_as_well'),
  'I want to replace_this and overwrite.'
);
```

**Two problems with it:**

- It's kind of a mess every time it's written.
- I need to start with all the keys and then all the values. A key/value pair is more natural for humans.

## Solution

**Toolkit**

Remove `jens_` prefix and add it to the `str` class:

```php
class jens_str {
  public static function replace($string, $array) {
    foreach( $array as $key => $value ) {
      $string = str_replace($key, $value, $string);
    }
    return $string;
  }
}
```

**In the template/plugin:**

```php
$array = array(
  'replace_this' => 'with_this',
  'overwrite' => 'this_as_well'
);

echo jens_str::replace('I want to replace_this and overwrite.', $array);
```

`str::replace` is missing in the Toolkit. Milestone 2.5? Copy/paste.

**Comment by lukasbestle** [comment]
This is a great idea. So great that even the PHP team had it. :)

```
echo strtr('I want to replace_this and overwrite.', $array);
```

Pretty hidden feature, yes. ;)
