### ISSUE TITLE
Routes default to GET, but HEAD should return the same

### ISSUE THREAD

**Issue by sebsel** [getkirby/toolkit#210]
I first filed this issue [here](https://github.com/getkirby/kirby/issues/538).

When you change [this line](https://github.com/getkirby/toolkit/blob/master/lib/router.php#L115) to:
```php
      'method'    => 'GET|HEAD',
```

It is solved :)

![schermafbeelding 2017-01-16 om 14 16 14](https://cloud.githubusercontent.com/assets/16517999/21984470/5d470438-dbf6-11e6-862d-616d80788b7d.jpg)

**Comment by lukasbestle** [comment]
Closing this until there is a proper solution. Discussion continues in getkirby/kirby#538.
