### ISSUE TITLE
Checks fail on MessageFormatter

### ISSUE THREAD

**Issue by sebsel** [getkirby/toolkit#221]
(I know you just closed issue #208, but I can't reopen, and it's kind of a new point now.)

Seems like neither Travis, my computer nor my server has MessageFormatter installed, so it's not as standard as was suggested by @lukasbestle. I can add it myself on my computer, but I don't have that kind of access on my server ATM (shared host ftw).

It also means that anyone who wants to use this in his/her plugin, makes the plugin require MessageFormatter. Sure, it's powerful, but if it's not reliably available, you can't use it.

**Comment by bastianallgeier** [comment]
I agree with @sebsel here. MessageFormatter really doesn't seem to be as widely available as I thought. I moved to str::template for now, which allows simple string replacements with `{var}` syntax. We can move to MessageFormatter once it has more support.
