### ISSUE TITLE
Allow cache to be extended with additional drivers

### ISSUE THREAD

**Issue by nblackburn** [getkirby/toolkit#230]
Cache doesn't look like it can be extended in the same was as `thumb` and `email`, it would be nice if it could so additional cache drivers could be implemented without hacking the core.

See #229

**Comment by lukasbestle** [comment]
You can just define the cache driver class in a plugin. If it's in the correct namespace, it will be picked up automatically.

**Comment by nblackburn** [comment]
@lukasbestle What would that namespace be as you don't seem to have one for Toolkit in general.

**Comment by lukasbestle** [comment]
Well, `Cache\Driver`. :)

**Comment by nblackburn** [comment]
@lukasbestle Yeah, that doesn't work.

**Comment by lukasbestle** [comment]
You are right, this is a loading order issue.

Kirby first initializes the cache as some plugins need the cache to work. But if the cache driver is defined inside a plugin, the cache can't be initialized without first loading the plugin.

As you can see, we can't really fix this as loading plugins before initializing the cache would break the plugins that depend on the cache.
You can however load your cache driver from a [custom `site.php` file](https://getkirby.com/docs/developer-guide/configuration/folders#site-php), it will then be available before Kirby needs the class.

Another thing: You call your redis driver class `RedisDriver`. The other drivers are just called like `Redis`. But this is not related to this issue.

**Comment by nblackburn** [comment]
@lukasbestle Kind of defeats the point of being a plugin if it requires a lot of work from the user.

**Comment by lukasbestle** [comment]
Yes, I agree with you that this does not really make sense as a plugin. I didn't know that this won't work before you tested it. :)
But as I outlined above, there is just no other way.

**Comment by nblackburn** [comment]
@lukasbestle Shame, i feel this is best in the core but understand the dependencies are a problem.
