### ISSUE TITLE
suggestion: automatic ace conversion for redirects

### ISSUE THREAD

**Issue by bnomei** [getkirby/toolkit#232]
using header redirect to an url with german umlaut does not work. one needs to convert to ace using `idn_to_ascii()`. a simple check might be comparing `$url` and `htmlentities($url)`.

since toolkit `redirect` is used kirbys `go()` helper and the `v::url()` and `url panel field` accepts idn formatted urls (with german umlaut) one might expect this to work out of the box, but it does not.

so maybe the toolkit redirect class could be extended to handle idn formated urls automatically.

example url in case you don't have one in mind: http://architekturgespräche.de

**Comment by lukasbestle** [comment]
This is now implemented on the develop branch along with other improvements to IDN handing.
