### ISSUE TITLE
a::missing reports 0 value

### ISSUE THREAD

**Issue by bnomei** [getkirby/toolkit#233]
`a::missing` should only report missing keys not check if value is `0` or `null`, right?

```php
$data = ['hello' => true, 'world' => 0];
$missing = a::missing($data, ['hello', 'world']);
a::show($missing);
```

results in

```
Array
(
    [0] => world
)
```

**Comment by texnixe** [comment]
The description of the method is this:

> Checks for missing elements in an array
> This is very handy to check for missing
> user values in a request for example.

According to this method description, the methods checks if a variable is empty, and a variable is empty if it returns false.

So I think the method does what it is supposed to do?

**Comment by bnomei** [comment]
I do not agree. the example provided is all about checking **keys** (not values). so i thought i was a array version of `array_key_exists`.

i was reading the desc here.
https://getkirby.com/docs/toolkit/api/a/missing

> Checks for missing elements in an array. [...]
> An array of **required keys** [...]
> An array of missing fields. If this is empty, nothing is missing.

There is nothing mentioned about checking values just about **required keys**.

about checking user values in a request... i just did that. my radio list has 0 based index and selecting the first entry failed. the key existed but the value was 0.

**Comment by texnixe** [comment]
Well, maybe, but what the method actually does it this:

```
  public static function missing($array, $required=array()) {
    $missing = array();
    foreach($required AS $r) {
      if(empty($array[$r])) $missing[] = $r;
    }
    return $missing;
  }
```

**Comment by Sija** [comment]
@texnixe Problem is that php's `empty` function treats `0` as empty, along with `''`, `null` and `false` which is counter-intuitive to this helper usecase.

**Comment by bnomei** [comment]
yeah. i know. thats why i have an *issue* with this function. the description and example do not match the code. at least update the docs in code and in the kirby/docs so ppl know it will [check values for FALSE](http://php.net/manual/en/function.empty.php).

- "" (an empty string)
- 0 (0 as an integer)
- 0.0 (0 as a float)
- "0" (0 as a string)
- NULL
- FALSE
- array() (an empty array)
- $var; (a variable declared, but without a value)

**Comment by texnixe** [comment]
Yes, maybe the example is misleading, it's taken from the source code.

**Comment by bnomei** [comment]
i understand what the intended usecase of the helpers code is. but something like `a::findEmpties` would be a more fitting name imho then. it is not about `missing`keys at least.

@texnixe i will leave this issue open for now. please do close it if you consider it solved.

**Comment by bnomei** [comment]
maybe adjust the Test as well?
https://github.com/getkirby/toolkit/blob/84530101e95e8ca7ffc4f350b409b7b7c0ce3feb/test/ATest.php#L97

**Comment by texnixe** [comment]
I've updated the documentation, I guess if the method wanted to check for missing keys, it would have used `array_key_exists`, but who am I to read peoples minds… :wink:

**Comment by Sija** [comment]
In my book `'0'` is definitely **not** missing, so this function is to say the least counter-intuitive if not simply buggy.

**Comment by texnixe** [comment]
> In my book '0' is definitely not missing,

I agree, its a value after all.

**Comment by lukasbestle** [comment]
I agree that using `empty` for this is a bug. The intention *was* to flag empty inputs (otherwise you could just use `array_key_exists()`), but not to flag non-actually-empty inputs like `0` and `"0"`. We will fix this in the next version.

**Comment by lukasbestle** [comment]
This is now fixed on the develop branch by only flagging elements that either don't exist at all or are `null`. All other falsy values like `""` and `0` are no longer flagged.
