### ISSUE TITLE
PHP 7.1.1.: ErrorException in dimensions.php

### ISSUE THREAD

**Issue by olliengel** [getkirby/toolkit#241]
Hi, 

when switching to PHP 7.1.1 thumb creation fails with this Exception:

> Whoops\Exception\ErrorException thrown with message "A non well formed numeric value encountered
> …/vendor/getkirby/toolkit/lib/dimensions.php186 

`$this->width  = round($fit * $ratio);`

Page is rendering fine with PHP version < 7.1.1 (tested on MAMP with 5.6.30 and 7.0.15)

As a workaround I used the type casting for the $fit parameter:  

`$this->width  = round((int)$fit * $ratio);`

This is working fine for me but maybe there is a better approach to fix this...

**Comment by lukasbestle** [comment]
Note to myself: We need to find out why `$fit` is a non-numeric string in the first place.

**Comment by lukasbestle** [comment]
I have tested this with PHP 7.1 but can't reproduce this. The `$fit` variable is never non-numeric.
Could you please post a code snippet of your thumb generation that allows me to reproduce the issue?

**Comment by olliengel** [comment]
Oh, my bad! Obviously I had used "px" since ancient times in this specific call and this had caused no errors before:  

`thumb($image, array('height'=>'180px'))`

Sorry for any trouble caused...
