### ISSUE TITLE
Idea : conditional check for the css() and js() helpers

### ISSUE THREAD

**Issue by manuelmoreale** [getkirby/toolkit#245]
Right now, there's no built in way to check if a script/stylesheet needs to be loaded in a page.
We can use a combination of `e()` and `js|css/()` and do something like this...

```
e(condition , js('assets/js/script.min.js'))
```

...but would nice to have this included as a third parameter, so something like this
```
js('assets/js/script.min.js' , true , condition)
```

Just an idea 😉

**Comment by lukasbestle** [comment]
Using `e` for this is pretty straightforward in my opinion. Do you have a use-case where a condition param would be more useful?

**Comment by manuelmoreale** [comment]
I agree, it is pretty straightforward and I don't have a case where it's more useful because it actually isn't since at the end of the day it's the same functionality.

It's just a matter of convenience to have all in one function and I personally think is nice to write things in a more compact way.

But mine was just an idea, definitely not something we **need**, plenty of alternative solutions available.

Most of the time the `js('@auto')` does the job perfectly well but there are times when you need to include a bunch of different things in one page and you can't really bundle them together.

Anyway, as I said, just a suggestion. Feel free to label it as an idea or close it/delete it
