### ISSUE TITLE
url::unIdn adds slash in front of query

### ISSUE THREAD

**Issue by vuvvn** [getkirby/toolkit#249]
Passing url like this
http://site.com/something?param=value
adds slash after "something". Therefore this code
`die(var_dump(url::unIdn('http://site.com/something?param=value')));`
produces the following output:
`string(38) "http://site.com/something/?param=value"`

That affects using go() to redirect to servers where that slash matters.

**Comment by lukasbestle** [comment]
You are right, another edge case for `url::build()`. I have fixed this on the develop branch and added unit tests for a few other cases. :)
