### ISSUE TITLE
Invalid YAML encoding

### ISSUE THREAD

**Issue by florianpircher** [getkirby/toolkit#252]
`yaml::encode` does not always return valid YAML.

Minimal example:

```php
$data = array('username' => '@example');
$yaml = yaml::encode($data);

// $yaml = "username: @example\n"
```

YAML reference [on Invalid use of Reserved Indicators](http://www.yaml.org/spec/1.2/spec.html#id2774228).

**Comment by Zegnat** [comment]
IIRC Kirby is using [YAML 1.0](http://yaml.org/spec/1.0/) which is pretty silent on this invalid use.

**Comment by florianpircher** [comment]
Thanks for the info! I discovered this behavior while developing a plugin and could not trace it back to anything. I will close this issue, because within the context of YAML 1.0 this is not an issue anymore.
