### ISSUE TITLE
Feature: webp image format

### ISSUE THREAD

**Issue by marcobiedermann** [getkirby/toolkit#254]
It would be great to also create a `webp` version of images which will save a lot of bytes to enhance the load time.

The SimpleImage library, which is already been used does support this conversion.
My goto would be to add an option `ENABLE_WEBP` and create a webp version from jpg or png next to it. Than you have to add both sources via `picture` element

```html
<picture>
  <source src="path/to/image.webp" type="image/webp">
  <img src="path/to/image.png">
</picture>
```

I also suggest updating the library from 2.5.5 to the current 3.3.3 or even better to load it via composer. This way it is easier to update and maintain.

**Comment by lukasbestle** [comment]
I have noted this down for Kirby 3.
