### ISSUE TITLE
Localhost URL Validation Issue

### ISSUE THREAD

**Issue by afbora** [getkirby/toolkit#255]
https://github.com/getkirby/toolkit/blob/4720c7584f770004e1c20ca6bb03183fce52ad66/lib/v.php#L134

Above URL regex validation doesnt working for localhost like that:

    http://localhost/test/ > FALSE
    http://www.localhost/test/ > TRUE
    http://www.google.com > TRUE

Kirby 2.5.5 Version

**Comment by lukasbestle** [comment]
Please read the comment above that line. There just isn't a proper validation regex that works for every kind of URL.
I have noted this down for Kirby 3, we will try to find a better way of validating URLs than using a regex.
