### ISSUE TITLE
str::encoding should be set to strict mode when using mb_detect_encoding

### ISSUE THREAD

**Issue by georgobermayr** [getkirby/toolkit#264]
Hi,

we are using `str:: utf8 ` to convert input data from a GET request to UTF-8. Unfortunately we have some issues (in our server environment?) that the underlying `str::encoding` function somethings returns the wrong encoding for the string (UTF-8 instead of iso-8859-1 for instance) and therefore causes the `iconv` function in `str::convert` to crash. 

We nailed down the issue to the `return mb_detect_encoding($string, 'UTF-8, ISO-8859-1, windows-1251');` in `str::encoding`. If we change this to `return mb_detect_encoding($string, 'UTF-8, ISO-8859-1, windows-1251', true);`, enabling the strict mode in `mb_detect_encoding`, detection of the encoding works reliable in our tests. 

Is it possible to change this?

Kind regards,
Georg

Envorinoment: MAMP 4.2.1 with PHP 7.1.8

**Comment by lukasbestle** [comment]
I can reproduce this and fixed it on the develop branch.
