### ISSUE TITLE
security headers for cookies. secure and httponly?

### ISSUE THREAD

**Issue by bnomei** [getkirby/toolkit#267]
i am using kirby for a ssl enabled (letsencrypt, `c::set('ssl', true)` ) website. 
but i get warnings for [cookie http headers](https://securityheaders.io/?q=https%3A%2F%2Fwww.juliankraan.com&followRedirects=on), whats wrong?

maybe case `httpOnly` must match or missing semicolon?

**Set-Cookie**
```
kirby_session=6u6hb25027kqkud167gkt3ol85; path=/
kirby_session=6u6hb25027kqkud167gkt3ol85; path=/; secure; httponly
```

**Comment by lukasbestle** [comment]
Well, that's strange. Kirby should not set two cookies, only one. I will investigate.

**Comment by texnixe** [comment]
However, we had issues with 2 Cookies in the past: https://forum.getkirby.com/t/set-cookie-twice/5444?
