### ISSUE TITLE
[lib email] SMTP implementation

### ISSUE THREAD

**Issue by kouinkouin** [getkirby/toolkit#276]
Hi,

Is there a reason for the absence of SMTP "email service" ?

I need it, so if the reason if the time, I can PR my developments.
Else, maybe am I wrong about something of Kirby design (architecture, not graphic...) ?

**Comment by lukasbestle** [comment]
Kirby 3 will have a rewritten email class, so we can't implement this for Kirby 2 as that would be double the work. However SMTP will most likely be supported in Kirby 3 out of the box.
