### ISSUE TITLE
refactor tpl-class to allow site-specific implementations

### ISSUE THREAD

**Issue by stmh** [getkirby/toolkit#29]
Hi,

I am currently working on refactoring Kirby and its toolkit to allow custom implementations of the tpl-class. I have currently a working HAML-template-implementation (using a fork of [MtHaml] (https://github.com/stmh/MtHaml)) which I inject into index.php. It works nicely and the template-files are very easy to read and understand. Performance wise there's no great difference, as the HAML-files gets compiled into php-files which get cached on the file-system.

The changes are minor:
* remove all mentions of '.php' for template-files in toolkit and other parts
* rewire all calls for checking the existence of a template file into the tpl-class using a static function

Is there any interest? If yes, I can try to submit a pull-request, but that's difficult, because the changes are spread over 3 repositories.

cheers,
Stephan

**Comment by namaless** [comment]
I think we need this, for a moment i see the development branch working fine for extend the markdown parser and another one, i think the best way is create a new template interface with base methods and implement with the kirby template. For extend with our template engine simple change the callback in the config, for a moment waiting the other features, the template engine isn't important i think.
