### ISSUE TITLE
helpers.php csfr function, should that be CSRF?

### ISSUE THREAD

**Issue by zzzzBov** [getkirby/toolkit#46]
`csfr` looks like a function used for [Cross-site request forgery][1] mitigation. If that's the case, shouldn't it be named `csrf`? Am I misunderstanding it's purpose?

[1]: http://en.wikipedia.org/wiki/Cross-site_request_forgery

**Comment by bastianallgeier** [comment]
Ok, this is seriously embarassing! I'm sitting in front of this for ages and never saw the typo. That's just plain stupid. I guess you really get routine-blinded after a while. I will rename it.

**Comment by zzzzBov** [comment]
no sweat, tyops happen. Better a misspelling than a security hole.

**Comment by bastianallgeier** [comment]
It's already renamed in the develop branch, so I'm closing this. thanks for the heads-up. At list I was very consistent with my typo as it seems. Must have pretty much burnt into my brain that way around :)
