### ISSUE TITLE
$pagination->pageUrl($page) does not respect `url` config option

### ISSUE THREAD

**Issue by grahamharper** [getkirby/toolkit#54]
If I set the `url` option in my config this does not appear to be used when returning a page url with `pageUrl()`.

I can pass the site url as an argument when I call paginate() on a collection but I this isn't very convenient.

Any thoughts or am I missing something here?

**Comment by grahamharper** [comment]
Ok I did a little more digging and this is happening because the `base()` method of the `Url` class builds Urls using server variables and doesn't respect the `url` config option.

**Comment by wtip** [comment]
You wouldn't happen to have a patch for this would you?

**Comment by wtip** [comment]
So I'm not sure this is actually a problem with the `Url` class.

I discovered it's possible to pass a URL when calling paginate like this: `paginate(10, array('url' => 'http://getkirby.com'))`
so my workaround for now is to use `paginate(10, array('url' => $page->url()))`

I am not sure if this is the best solution but I guess we will have to wait for Bastian to comment.

**Comment by bastianallgeier** [comment]
This is finally fixed on the develop branch and will be in the next stable release.
