### ISSUE TITLE
Bug: setting limit, but no offset

### ISSUE THREAD

**Issue by distantnative** [getkirby/toolkit#66]
I think I might have found a bug in regard to the limit method:

```php
$db->table('trips')->order('start ASC')->order('end ASC')->where('start', '>', date('Y-m-d'))->debug()->all()
```

which results into

```sql
SELECT * FROM trips JOIN places ON trips.place = places.id WHERE start > "2015-03-16" ORDER BY end ASC LIMIT , 5
```

And mysql throws me an error, because of ```LIMIT , 5```. If I add ```->offset(0)```, I get ```LIMIT 0,5``` and it works.

**Comment by bastianallgeier** [comment]
Hm, could you paste the full example for that query? I'm not sure where the limit is coming from at all.

**Comment by distantnative** [comment]
Oh boy, stupid me.. ofc:

```php
$db->table('trips')->order('start ASC')->order('end ASC')->where('start', '>', date('Y-m-d'))->limit(5)->all()
```

**Comment by bastianallgeier** [comment]
Hm, I just tried to replicate this but didn't run into the same bug. Do you use the develop version of the toolkit?

**Comment by distantnative** [comment]
No, the stable one that comes with the starterkit atm

**Comment by distantnative** [comment]
Uhh, just checked and now it works. Might have been the combination with using two order statements? I don't know, but it works :D thanks for trying to help!
