### ISSUE TITLE
Thumbs use absolute path instead of the relative path

### ISSUE THREAD

**Issue by hydrapolic** [getkirby/toolkit#69]
Suppose we create a kirby site and we keep the files under `/var/www/kirby`. We also use thumbs, so they are generated to `/var/www/kirby/thumbs`. 

Then we move this to production under directory `/var/www/sitename` and we don't have `/var/www/sitename/thumbs` writable. This way, the thumbs will fail to work, because the absolute path has changed.

https://github.com/getkirby/toolkit/blob/develop/lib/thumb.php:
```php
$destination->filename = str::template($this->options['filename'], array(
  'hash' => md5($this->source->root() . $this->settingsIdentifier()),
));
```

https://github.com/getkirby/toolkit/blob/develop/lib/media.php:
```php
public function __construct($root, $url = null) {
  $this->root = realpath($root);
}
```

So it means there is strict requirement on thumbs that the directories cannot be different. Wouldn't it make more sense to use relative paths?

When I have a picture under `/var/www/kirby/content/dir/test.jpg`

The md5 should be calculated from `content/dir/test.jpg` and not `/var/www/kirby/content/dir/test.jpg`.

**Comment by davidburger** [comment]
git diff lib/thumb.php
diff --git a/lib/thumb.php b/lib/thumb.php
index 956e2d5..6aa9d40 100644
--- a/lib/thumb.php
+++ b/lib/thumb.php
@@ -40,6 +40,11 @@ class Thumb extends Obj {
   public $options     = array();
   public $error       = null;
 
+ /**
+  * @var string
+  */
+  protected $hash = null;
+
   /**
    * Constructor
    *
@@ -60,7 +65,7 @@ class Thumb extends Obj {
       'safeFilename' => f::safeName($this->source->name()) . '.' . $this->extension(),
       'width'        => $this->options['width'],
       'height'       => $this->options['height'],
-      'hash'         => md5($this->source->root() . $this->settingsIdentifier()),
+      'hash'         => $this->getHash(),
     ));
 
     $this->destination->url  = $this->options['url'] . '/' . $this->destination->filename;
@@ -95,6 +100,28 @@ class Thumb extends Obj {
 
   }
 
+
+  /**
+   * thumbnail hash calculation (consistent between different linux environments)
+   * @return string
+   */
+   public function getHash()
+   {
+     if (null === $this->hash) {
+        $projectDir = Kirby::instance()->roots->index;
+        $relativePath = $this->source->root();
+        $position = strpos($relativePath, $projectDir);
+
+        if ($position === 0) {
+            $relativePath = substr($relativePath, strlen($projectDir));
+            $relativePath = trim($relativePath, DIRECTORY_SEPARATOR);
+        }
+        $this->hash = md5($relativePath . $this->settingsIdentifier());
+     }
+     return $this->hash;
+   }

**Comment by namaless** [comment]
Sorry but when you move from development to production you not delete all cache/thumbs file? In this case the situation is fixed no?

**Comment by hydrapolic** [comment]
I don't delete the thumbs, I would like production to be as static as possible.

The other thing is, that if you have 2 servers AND the thumbs writable, then:
- request comes to server1, it generates the thumbs and returns the links
- the requests for thumbs come to server2 where they are not available and then cause 404

This happens when you have a round-robin load-balancer.

**Comment by namaless** [comment]
Ah ok thanks for more info.

**Comment by bastianallgeier** [comment]
The new thumb core component in 2.3 uses an entirely different way to store files, which will no longer rely on absolute paths.
