### ISSUE TITLE
missing reply-to when sending via Mailgun

### ISSUE THREAD

**Issue by groenewege** [getkirby/toolkit#71]
Hello,

I am using the kirby-uniform plugin to send a contact form.
This plugin populates the reply-to field of the email with the senders email address.
When using Mailgun as the mail service, the reply-to field is not set and so the senders email address is lost.

I believe the Mailgun API allows setting the reply-to header by using the h:Reply-To parameter.
https://documentation.mailgun.com/api-sending.html#sending

best regards,
gunther

**Comment by bastianallgeier** [comment]
I just implemented this on the develop branch.
