### ISSUE TITLE
email – Additional sender name is removed from "From:" 

### ISSUE THREAD

**Issue by ralfgoeke** [getkirby/toolkit#76]
The PHP mail() function is capable of sending a name along with the address, like so:

```John Doe <john.doe@example.com>```

Seems like the toolkit removes anything but the mail address in line 31 using the extractAddress method:

```
public function __set($key, $value) {
    if(in_array($key, array('to', 'from', 'replyTo'))) {
      $this->$key = $this->extractAddress($value);
    } else {
      $this->$key = $value;
    }
  }
```

I don't really now how to fix/improve this, so sorry for not opening a pull request instead of opening an issue.

**Comment by mzur** [comment]
Another question would be *why* the email address is stripped like that. Maybe there is a good reason for that. I would appreciate a possibility to add a name to the address, too.

**Comment by bastianallgeier** [comment]
The only reason for this is that I actually didn't know that you can pass it like that and it will work. Shame on me for being a n00b here!
