### ISSUE TITLE
url::hasQuery does not exist

### ISSUE THREAD

**Issue by mzur** [getkirby/toolkit#77]
I just attempted to use the `remote::get` method [but it failed](https://github.com/getkirby/toolkit/blob/e712a46bffc5957044dbf71d9a5b735fdd9540db/lib/remote.php#L207) because of the apparently nonexistent `url::hasQuery` method. I couldn't find this method in any commit to the `Url` class. Was it accidentally removed sometime?

**Comment by distantnative** [comment]
It is there for me - lines 127-133

![screen shot 2015-05-05 at 09 37 24](https://cloud.githubusercontent.com/assets/3788865/7468550/61429f56-f30a-11e4-8b1e-8b8521850626.png)

**Comment by bastianallgeier** [comment]
This is fixed in the latest version on the develop branch.
