### ISSUE TITLE
Double stripslashes?

### ISSUE THREAD

**Issue by Boycce** [getkirby/toolkit#85]
When GPC magic quotes was enabled on my server, the double stripslash command https://github.com/getkirby/toolkit/blob/develop/lib/str.php#L573 was removing necessary slashes in my content. I removed one `stripslashe` command and works fine. I just want to double(lol) check the reason for the two before I submit a PR.

**Comment by bastianallgeier** [comment]
This is some legacy stuff, which I can't explain fully anymore to be honest. I just fixed this.

**Comment by Boycce** [comment]
sweet!
