### ISSUE TITLE
v::url in development

### ISSUE THREAD

**Issue by dervondenbergen** [getkirby/toolkit#90]
The regular expression for [v::url](https://github.com/getkirby/toolkit/blob/master/lib/v.php#L119) prevents using a local server for development.

Domains like `http://localhost:9000/my/option/data` aren't a valid url. Therefore they won't be fetched as dynamic options. Using an absolute url like `/my/option/data` would be also useful, because in an production environment are the paths possibly the same but the rest of the url not.

**Comment by bastianallgeier** [comment]
I fixed this in the panel code on the develop branch. It will be in the next release.

**Comment by dervondenbergen** [comment]
:+1:
