### ISSUE TITLE
Email: Format "Name <hi@email.com>" is not working

### ISSUE THREAD

**Issue by Targoran** [getkirby/toolkit#95]
The PHP mail function is able to send email in the format `Name <hi@gmail.com>` and in the [kirby email plugin](http://getkirby.com/blog/email-plugin) this seems to work as well.

But in the current Kirby Version (2.1.0) this does not seem to work.
When using an e-mail address formatted like above for the 'to' field, I'm getting a **Invalid recipient** error. 

The reason seems to be that Kirby evaluates the e-mail against PHPs FILTER_VALIDATE_EMAIL.

Would be great to have this working again.

**Comment by bastianallgeier** [comment]
This is now fixed on the develop branch.
